### ISSUE TITLE
Cannot snapshot empty string

### ISSUE THREAD

**Issue by chrisbreiding** [bahmutov/snap-shot-core#25]
Attempting to snapshot an empty string results in the following error:

```
Error: expected string value 
      at lazyAssLogic (node_modules/lazy-ass/index.js:110:14)
      at lazyAss (node_modules/lazy-ass/index.js:115:28)
      at exportText (node_modules/snap-shot-core/src/file-system.js:70:3)
      at Object.keys.forEach.testName (node_modules/snap-shot-core/src/file-system.js:98:12)
      at Array.forEach (native)
      at Object.saveSnapshots (node_modules/snap-shot-core/src/file-system.js:90:26)
      at storeValue (node_modules/snap-shot-core/src/index.js:86:8)
      at setOrCheckValue (node_modules/snap-shot-core/src/index.js:159:7)
      at snapShotCore (node_modules/snap-shot-core/src/index.js:183:12)
      at snapshot (node_modules/snap-shot-it/src/index.js:58:10)
       ...
```

From this error, it wasn't clear that the empty string was what I had passed to `snapshot()`. This should probably be allowed anyway since an empty string could be a perfectly valid value.

**Comment by bahmutov** [comment]
What's the test here? just `snapshot('')`? 

I honestly feel empty / null / undefined values should not be stored as a snapshot. Snapshots should be for large, complex values

**Comment by chrisbreiding** [comment]
The problem is that the test is something more like `snapshot(logger.print())`. It took a good bit of debugging to realize that `logger.print()` was returning an empty string and that the problem was that I was passing an empty string to `snapshot`. At the very least, it would be nice to have a better error message to make it clear that the snapshot is failing because I attempted to snapshot an empty string.

**Comment by bahmutov** [comment]
that's a good point, I want to make this message better too

**Comment by bahmutov** [comment]
Will throw a good text message
```
Error: Cannot store empty / null / undefined string as a snapshot value.
Seems the value you are trying to store in a snapshot "test"
is empty. Snapshots only work well if they have actual content
to store. Otherwise, why bother?
```

**Comment by bahmutov** [comment]
Version `4.3.0` has been published to NPM. The full release note can be found at [snap-shot-core/releases/tag/v4.3.0](https://github.com/bahmutov/snap-shot-core/releases/tag/v4.3.0).

**Tip:** safely upgrade dependency snap-shot-core in your project using [next-update](https://github.com/bahmutov/next-update)
