### ISSUE TITLE
sort out issues with CI

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot-core#250]
Currently reports a broken build because of missing file?!

```
  1) "before each" hook for "re-saves snapshots without sorting":
     Error: ENOENT: no such file or directory, open '/home/travis/build/bahmutov/snap-shot-core/bin/test-resave/snapshot.js'
      at Object.openSync (fs.js:438:3)
      at Object.writeFileSync (fs.js:1189:35)
      at Context.beforeEach (bin/resave-snapshots-spec.js:45:6)
```

**Comment by bahmutov** [comment]
resolved
